### ISSUE TITLE
与一些会播放自定义音乐的MOD一起使用时会崩溃

### ISSUE THREAD

**Issue by pphelper** [BowenJXD/HSRMod#1]
芙莉莲MOD角色战败时会播放一段音乐
将HSR和芙莉莲一起激活时选择芙莉莲MOD角色并战败就会直接崩溃
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.54.1)
 - stslib (2.11.0)
 - loadout (1.1.0)
 - FrierenMod (2.0.4)
 - HSRMod (2.2.1)

Mods in stacktrace:
 - FrierenMod (2.0.4)
Cause:
com.badlogic.gdx.utils.GdxRuntimeException: Unknown file extension for music: audio/music/Frieren_DeathStinger
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:126)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:41)
	at com.megacrit.cardcrawl.audio.MainMusic.newMusic(MainMusic.java:109)
	at com.megacrit.cardcrawl.audio.TempMusic.getSong(TempMusic.java:49)
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:52)
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:42)
	at com.megacrit.cardcrawl.audio.MusicMaster.playTempBgmInstantly(MusicMaster.java:116)
	at FrierenMod.patches.AudioPatch$PatchDeathScreen.calc(AudioPatch.java:143)
	at com.megacrit.cardcrawl.screens.DeathScreen.<init>(DeathScreen.java:160)
	at com.megacrit.cardcrawl.screens.options.ConfirmPopup.yesButtonEffect(ConfirmPopup.java:264)
	at com.megacrit.cardcrawl.screens.options.ConfirmPopup.updateYes(ConfirmPopup.java:149)
	at com.megacrit.cardcrawl.screens.options.ConfirmPopup.update(ConfirmPopup.java:135)
	at com.megacrit.cardcrawl.screens.options.SettingsScreen.update(SettingsScreen.java:29)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2555)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
和鹿目圆香MOD也有相似的问题对战魔女之夜或碎心成功后也会播放特殊音乐
Mod list:
 - basemod (5.54.1)
 - stslib (2.11.0)
 - loadout (1.1.0)
 - HSRMod (2.2.1)
 - actlikeit (1.2.8)
 - VideoTheSpire (1.0.0)
 - KanameMadoka (1.31)

Mods in stacktrace:
 - KanameMadoka (1.31)
Cause:
com.badlogic.gdx.utils.GdxRuntimeException: Unknown file extension for music: audio/music/BOSS_Final
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:126)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:41)
	at com.megacrit.cardcrawl.audio.MainMusic.newMusic(MainMusic.java:109)
	at com.megacrit.cardcrawl.audio.TempMusic.getSong(TempMusic.java:49)
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:52)
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:42)
	at com.megacrit.cardcrawl.audio.MusicMaster.playTempBgmInstantly(MusicMaster.java:116)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.playBgmInstantly(AbstractRoom.java:165)
	at MadokaMod.monsters.Boss.Act4.Walpurgisnacht.buttonEffect(Walpurgisnacht.java:276)
	at MadokaMod.monsters.Boss.Act4.Choice.eventAction.update(eventAction.java:23)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:283)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

Mods in stacktrace:
 - KanameMadoka (1.31)
Cause:
com.badlogic.gdx.utils.GdxRuntimeException: Unknown file extension for music: audio/music/ending
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:126)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newMusic(OpenALAudio.java:41)
	at com.megacrit.cardcrawl.audio.MainMusic.newMusic(MainMusic.java:109)
	at com.megacrit.cardcrawl.audio.TempMusic.getSong(TempMusic.java:49)
	at com.megacrit.cardcrawl.audio.TempMusic.<init>(TempMusic.java:52)
	at com.megacrit.cardcrawl.audio.MusicMaster.playTempBgmInstantly(MusicMaster.java:155)
	at MadokaMod.Patch.EndSoundPatch.sound(EndSoundPatch.java:17)
	at com.megacrit.cardcrawl.rooms.TrueVictoryRoom.onPlayerEntry(TrueVictoryRoom.java)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2282)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2119)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.updateFading(AbstractDungeon.java:2848)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2517)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by BowenJXD** [comment]
是musicpatch用了replace的问题，已经在最新的commit里解决了，谢谢告知。
