### ISSUE TITLE
打完第二章BOSS后闪退

### ISSUE THREAD

**Issue by hyperv0id** [BowenJXD/HSRMod#2]
打完第二章BOSS后闪退，初步判断为遗物生成逻辑有问题

## 启用模组
```
basemod@5.54.1        BaseMod
stslib@2.11.0        StSLib
Muelsyse_FimmlpS@0.9.5        Muelsyse_Mod(缪尔赛思)
downfall@5.2.04        Downfall
HSRMod@2.3.0        HSR【崩坏：星穹铁道】
Mostima@0.3.3        【明日方舟】莫斯提马
lingmod@0.1.4        Ling(明日方舟-令)
Reed_FimmlpS@0.9.0        Reed_Mod(焰影苇草)
Typhon_FimmlpS@0.9.3        Typhon_Mod
```
## 报错
```
Mods in stacktrace:
 - HSRMod (2.3.0)

java.lang.IllegalArgumentException: n must be positive
        at com.badlogic.gdx.math.RandomXS128.nextLong(RandomXS128.java:110)
        at com.badlogic.gdx.math.RandomXS128.nextInt(RandomXS128.java:99)
        at com.megacrit.cardcrawl.random.Random.random(Random.java:65)
        at hsrmod.utils.RewardEditor.getRelic(RewardEditor.java:192)
        at hsrmod.utils.RewardEditor.update(RewardEditor.java:74)
        at hsrmod.relics.starter.WaxRelic.update(WaxRelic.java:32)
        at com.megacrit.cardcrawl.core.OverlayMenu.update(OverlayMenu.java:71)
        at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2649)
        at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:876)
        at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```
## 修复意见
在hsrmod.utils.RewardEditor的getRelic方法中

```java
  if (pool.isEmpty()) {
     return "";
  } else {
// 此处relics在过滤后仍有可能为空，导致错误
// 需要再次判断relics是否为空
     List<String> relics = (List)pool.stream().filter((r) -> RelicLibrary.getRelic(r) instanceof BaseRelic).collect(Collectors.toList());
     String relic = (String)relics.get(AbstractDungeon.cardRandomRng.random(relics.size() - 1));
     pool.remove(relic);
     return relic;
  }
```

**Comment by BowenJXD** [comment]
已修复，感谢反馈~
